//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedJob
    {
        public int Id { get; set; }
        public int Pid { get; set; }
        public int Sid { get; set; }
        public string Date { get; set; }
        public string JobStatus { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
