//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.AppliedJobs = new HashSet<AppliedJob>();
            this.JobSaves = new HashSet<JobSave>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Titel { get; set; }
        public string JobDescription { get; set; }
        public string Location { get; set; }
        public string Program { get; set; }
        public string Skills { get; set; }
        public string DeadLine { get; set; }
    
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
        public virtual CompanyProfile CompanyProfile { get; set; }
        public virtual ICollection<JobSave> JobSaves { get; set; }
    }
}
